### ISSUE TITLE
Doesn't work correctly in Firefox

### ISSUE THREAD

**Issue by ajwinter** [NREL/floorspace.js#1]

**Comment by macumber** [comment]
Also internet explorer, Safari (iphone), etc

**Comment by ritwikagarwal** [comment]
Can someone point out what features of the web app are not working on firefox??
I tested the web app link and it works just fine on the firefox.

**Comment by shorowit** [comment]
Known issues on Firefox have since been fixed (by @bgschiller?). That said, the widget has seen far more testing on Chrome than Firefox, so I don't think any of us really know if there are lingering issues on Firefox.

**Comment by ritwikagarwal** [comment]
Hmm. I think there are no issues currently on the Firefox versions noticeable.There may be minor ones but to my knowledge the Firefox version is sufficient enough to produce a productive results.

**Comment by shorowit** [comment]
Cool, I will close the issue then. If anyone experiences any problems on Firefox in the future, please reopen this issue or open a new issue.
