### ISSUE TITLE
Config Initialization API

### ISSUE THREAD

**Issue by macumber** [NREL/floorspace.js#102]
When I load the editor in the OpenStudio application, I have a callback on page load that I can use to call javascript API methods.  I would like to call setConfig with the following options:

- [x] Set units to IP/SI
- [x] Enable or disable the place map dialog (if we have an existing JSON I will be calling doImport after this and don't want the dialog to show up before going away)
- [x] Set online to true/false (if we are offline I can set this so we don't try to load online mapping, or we can just let the app try and fail it if is graceful enough)
- [x] Function name to call when the document changes, this will be something like "osapp.onChange()", default will be to increment a counter
- [x] Set initial lat/lon in config

My thought is that there can be a call to setConfig in the Javascript on page load call back.  When I build the single page html using the ruby build.rb script, I can remove this code.  That way when you run the app as a standalone webpage you will get the default config.  When I call it in the OS App I will have to pass in the config manually.

**Comment by macumber** [comment]
For new files, I think I will start by passing in a new JSON file rather than letting the geometry editor provide one, so I'll want to call doImport but still allow the place map dialog

**Comment by gh-23378** [comment]
This is done, when Dan has had a chance to test it I will remove his test button and submit a PR.

**Comment by macumber** [comment]
I don't think this is fully working, maybe got stepped on by some other code changes.  Here are some quick tests I've done with the embeddable_geometry_editor.html.  For each test, I reload the page, then type these commands in the console.  If we call openFloorplan after any of these initial configurations, the data in the opened floorplan will override the initial configuration.

```
// new dialog should be shown with map button enabled but is not
window.api.setConfig({"showMapDialogOnStart": true, "online": true, "units": "ft"});
window.api.init();
window.api.importLibrary(JSON.stringify({}));

// new dialog should be shown with map button disabled but is not
window.api.setConfig({"showMapDialogOnStart": true, "online": false, "units": "ft"});
window.api.init();
window.api.importLibrary(JSON.stringify({}));

// new dialog is not shown (correct) but map is enabled, We should not show the map because we have no internet and we don't have a location chosen.
window.api.setConfig({"showMapDialogOnStart": false, "online": false, "units": "ft"});
window.api.init();
window.api.importLibrary(JSON.stringify({}));

// new dialog is not shown (correct) but map is enabled, We should not show the map because we don't have a location chosen.
window.api.setConfig({"showMapDialogOnStart": false, "online": true, "units": "ft"});
window.api.init();
window.api.importLibrary(JSON.stringify({}));
```
