### ISSUE TITLE
Need to support imperial units as well as metric

### ISSUE THREAD

**Issue by ljbrackney** [NREL/floorspace.js#69]
Need an option to switch from m to ft.  If this already exists, it wasn't obvious to me.

**Comment by macumber** [comment]
- [x] Allow configuring units in editor initialization config

**Comment by devKate** [comment]
" Ensure that opening files with different units correctly converts to current editor units
 Ensure that library/component files with units (e.g. window length) are converted to current editor units"
Those two items might not be relevant yet. Currently, there are no units on any library objects, and importing a full floor plan will also require importing the existing units setting from that floor plan.

**Comment by macumber** [comment]
The default_library.json file has "units": "ft", and windows like:

    {
      "id": null,
      "name": "Window F",
      "height": 3,
      "width": 4,
      "sill_height": 3
    }

So those should be interpreted as windows that are 3 ft x 4 ft, inserted 3ft above the ground

**Comment by macumber** [comment]
For 0.2 the units should just be locked to 'ft', this issue should stay open for future work

**Comment by macumber** [comment]
For 0.3 let's change ft/m to be label outside of grid spacing box, same thing for degree with north axis

**Comment by macumber** [comment]
In standalone mode, allow user to pick units in initial dialog

**Comment by bgschiller** [comment]
@macumber Instead of adding to the initial dialog modal, I put a toggle where the units display. The toggle can only be switched before geometry is drawn.

When we get full unit conversion working, the UI won't have to change. We'll just permit changing that select box at any time (even when geometry exists)
