### ISSUE TITLE
Strange Snapping Behavior with Rectangle Tool

### ISSUE THREAD

**Issue by ljbrackney** [NREL/floorspace.js#72]
Using rectangle tool results in weird snapping behavior for some geometries.  Note that spaces 1-2 and 1-6 should both be rectangles, but they were forced to snap to nearby space vertices.  This happens regardless of grid settings.  (On/off, 1ft/5ft)

![snap](https://user-images.githubusercontent.com/2230150/27366498-610e20a4-55fb-11e7-80b1-0891159298d7.png)

**Comment by macumber** [comment]
@ljbrackney FYI @devKate requested console errors if they exist for any issues

**Comment by ljbrackney** [comment]
No errors in console related to weird snapping behavior, but I see Duplicate vertex errors when trying to add some geometry.  Snapping behavior can be replicated by trying to create two adjacent rectangular spaces of slightly different heights.  If the height delta is sufficiently* small then the vertex of the second space snaps to the adjacent space's vertex as shown in my example.

* I've played with grid spacing, and it doesn't appear that has any bearing on where this starts happening.

**Comment by ljbrackney** [comment]
This screenshot shows more of the behavior.  If I made Space 1-2 a bit longer, the lower left corner would have snapped to Space 1-1's lower right corner.  You can see examples in spaces 1-4 and 1-5.  The above example shows an even worse case with Space 1-6, which snaps to the vertices of 1-4 and 1-5, dividing space 1-3.

![snap2](https://user-images.githubusercontent.com/2230150/27395314-356e2d68-5664-11e7-8c9e-060265e1ecc7.png)

**Comment by ajwinter** [comment]
@ljbrackney Just checking for testing purposes: when did you last update locally from develop?

**Comment by ljbrackney** [comment]
Rebuilt from develop around 8 or 9pm last night - included pull request 71.

**Comment by bgschiller** [comment]
@ljbrackney just made a change so that holding down shift will disable snapping behavior. Does that adequately address this issue?

**Comment by ljbrackney** [comment]
Shift drag seems to be working okay for ignoring the grid, but I'm still getting this weird snapping behavior.  You can get a sense of the progression in the attached images.  Things are going okay in the first image...

![image2](https://user-images.githubusercontent.com/2230150/28803467-a565c6e0-7611-11e7-8035-5143ecd9e83d.png)

Then I try to add this small space at the bottom as a rectangle that's not as long as the space above.  Ugh.  That's not what I wanted...

![image1](https://user-images.githubusercontent.com/2230150/28803472-b5cea678-7611-11e7-8fa7-7c13b2c4b67d.png)

Well I'll plow ahead with that long L-shaped corridor and see what happens...

![image](https://user-images.githubusercontent.com/2230150/28803416-3d0f724e-7611-11e7-9c4d-6850755b1dd1.png)

Even uglier.  All of this was done w/ shift dragging.

**Comment by ljbrackney** [comment]
If I set a fine grid and let rectangles snap to it then things are a bit better, but it seems like the editor is still trying to snap to the grid and space vertices simultaneously.  So I end up with "rectangles that aren't."  I could probably snap everything to a sufficiently fine grid, but I was trying to avoid relying on a grid so I could trace over my floorplan.

![image](https://user-images.githubusercontent.com/2230150/28803601-962cdc94-7612-11e7-98b9-ea7b08735cde.png)
